import './globals.css'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import { ThemeProvider } from '@/contexct/ThemeContecxt'
import AuthProvider from '@/components/AuthProvider/AuthProvider'

export const generateMetadata = (par: string) => {

  return {
    title: `${ par == typeof({}) ? 'My app' : `My app | ${par}` }`,
    description: 'Generated by create next app',
  }
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/logo.png"
          type="image/png"
        />
      </head>
      <body>
        <AuthProvider>
          <ThemeProvider>
            <div className="container">
              <Header />
              {children}
              <Footer />
            </div>
          </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
